### ISSUE TITLE
Jets-Experiment

### ISSUE THREAD

**Issue by snath99920** [virtual-labs/hydraulics-and-fluid-mechanics-iiith#148]
Description: Link description shows Soil Mechanics Lab. Opens to Hydraulics and fluid mechanics lab
Steps to reproduce the issue: Hydraulics and Fluid Mechanics lab->List of experiment->Jets experiment
Expected Result: Link description must be Hydraulics and Fluid mechanics lab
Actual result: Shows Soil Mechanics lab

![Screenshot from 2019-03-17 12-32-25](https://user-images.githubusercontent.com/40913303/54486635-bd5ddd00-48b0-11e9-845c-ec9f8fd7df6f.png)

**Comment by swastik24** [comment]
fixed 
commit id b91d370778314d94ba3f93c42c8d9996e3f0d548
